"""Hand-verified mappings used by build.py.

Every Arshad school below was checked by hand against the Kozhikode School Data
(state-syllabus master list), the CBSE and the ICSE directories.
"""

# Arshad "name @ place"  ->  ("M", master school name) | ("CBSE", s.no) | ("ICSE", code) | None
ARSHAD_MATCH = {
    "G V H S S @ Meenchanda": ("M", "G. V. H. S. S Meenchanda"),
    "Naduvattom A L P S @ Mathottam": ("M", "A. L. P. S. Naduvattom"),
    "Salafi E M S @ Mathottam": ("M", "Salafi E. M. L. P. School Mathottam"),
    "Govind Vilas A L P School @ Arakkinar": ("M", "Govindavilas A. L. P. S Naduvattam"),
    "Thattumkavu A M L P School @ Arakkinar": ("M", "Thattadathumkave A. M. L. P. S. Naduvattam"),
    "G H S S @ Beypore": ("M", "G. H. S. S. Beypore"),
    "G H S @ Beypore": ("M", "G. H. S. S. Beypore"),
    "G H S U P Section @ Beypore": ("M", "G. H. S. S. Beypore"),
    "G U P School @ Naduvattom Beypore": ("M", "G. U. P. S. Naduvattam"),
    "Apex International School @ Odumbra": ("CBSE", 9),
    "A L P School @ Odumbra": ("M", "A. L. P. S. Odumbra"),
    "G U P School @ Thiruvannur": ("M", "G. U. P. S. Thiruvannur"),
    "N S S U P School @ Meenchanda": ("M", "N. S. S. U. P. S. Beypore"),
    "G R F T H S S @ Beypore Port": ("M", "G. R. F. T. H. S. And V. H. S. S. Beypore"),
    "G R F T H S @ Beypore Port": ("M", "G. R. F. T. H. S. And V. H. S. S. Beypore"),
    "Jinarajadas A L P School @ Naduvattom": ("M", "Jinarajadas A. L. P. S. Naduvattam"),
    "A M U P School @ Kambilipparamba": ("M", "A. M. U. P. S. Kambliparamba"),
    "Govt Ganapat U P School @ Pokkunn": ("M", "G. G. U. P. S. Pokkunnu"),
    "C I R H S S @ Mathara": ("M", "CALICUT ISLAMIC RESIDENTIAL H. S. S"),
    "G L P School @ Iringallur": ("M", "G L P S IRINGALLUR"),
    "A L P School @ Olavanna": ("M", "A. L. P. S. Olavanna"),
    "Govt Ganapat Boys U P School @ Chalappuram": ("M", "Govt.Ganapat B.H.S Chalapuram"),
    "Govt Ganapat Boys H S @ Chalappuram": ("M", "Govt.Ganapat B.H.S Chalapuram"),
    "Govt Ganapat L P School @ Chalappuram": ("M", "Ganapath L. P. S. Chalappuram"),
    "Govt U P School @ Thali": ("M", "G. U. P. S. Thali"),
    "G L P School @ Kottummal, Thiruvannur": ("M", "G. L. P. S. Kottummal"),
    "Palat G U P School @ Thiruvannur": ("M", "Govt. U. P. School Palat"),
    "G L P School @ Kannancheri": ("M", "G. L. P. S. Kannancheri"),
    "R K Mission A L P School @ Kannancheri": ("M", "S. R. K. M. L. P. S"),
    "N S S H S @ Meenchanda": ("M", "N. S. S. H. S. S Meenchanda"),
    "A L P School @ Thalikkulangara": ("M", "Talikulangara A. L. P. S"),
    "R K Mission High School @ Kannancheri": ("M", "Ramakrishna Mission H. S. S"),
    "R K Mission Higher Secondary School @ Kannancheri": ("M", "Ramakrishna Mission H. S. S"),
    "Govt Ganapat Girls HS @ Chalappuaram": ("M", "G. G. Model G. H. S. S. Chalappuram"),
    "Govt Ganapat Girls HS (UP Section) @ Chalappuaram": ("M", "G. G. Model G. H. S. S. Chalappuram"),
    "Nirmal Hrudaya EMSchool @ Kaloor Roade": ("ICSE", "KE159"),
    "MIUPSchool @ Mooriyad": ("M", "M. I. U. P. S. Mooriyad"),
    "GLPSchool @ Aazhchavattom": ("M", "G. L. P. S. Azhchavattam"),
    "Govt HS @ Aazhchavattom": ("M", "G H S S Azhchavattom"),
    "ALP School @ Kommeri": ("M", "Kommeri. A. L. P. S"),
    "Sree Gokulam Public School @ Valayanad": ("CBSE", 84),
    "MIMLP School @ Puthiyapalam": ("M", "Muneerul Islam L. P. S."),
    "Zamorians HSS @ Thali": ("M", "Zamorin's H. S. S. Kozhikode"),
    "Zamorians UPSchool @ Thali": ("M", "Zamorin's H. S. S. Kozhikode"),
    "Zamorians HS @ Thali": ("M", "Zamorin's H. S. S. Kozhikode"),
    "Govt Achuthan Girls HS @ Chalappuram": ("M", "Govt. Achuthan G. H. S Chalappuram"),
    "Sapphire Central School @ Olavanna": ("CBSE", 76),
    "G L P School @ Olavanna": ("M", "G. L. P. S. Olavanna"),
    "G L P School @ Kacherikunn": ("M", "G. L. P. S. Kacherikkunnu"),
    "G L P School @ Parappil": ("M", "G. L. P.S. Parappil"),
    "G L P School @ Kinassery": ("M", "G. L. P. S. Kinasseri"),
    "Govt H S @ Kinassery": ("M", "G. V. H. S. S Kinassery"),
    "Govt H S (U P Section) @ Kinassery": ("M", "G. V. H. S. S Kinassery"),
    "Olive English Medium School @ Kinassery": ("M", "OLIVE ENGLISH MEDIUM HIGH SCHOOL"),
    "G L P School @ Kottooli": ("M", "G. L. P. S. Kottooli"),
    "Saraswathy Vidya Mandiram @ Kottooli": ("M", "ATHI VIDYA MANDIRAM ENGLISH MEDIUM HIGH SCHOOL, KO"),
    "A U P School @ Kottooli": ("M", "A. U. P. S. Kottooli"),
    "Govt U P School @ Civil Station": ("M", "G. U. P. S. Civil Station"),
    "Christuraja A L P School @ Malaparamba": ("M", "Christuraja L. P. S"),
    "J D T Islam Iqra E M S @ Vellimadakunnu": ("M", "J D T ISLAM IQRAA ENGLISH MEDIUM HIGH SCHOOL"),
    "St Joseph E M S @ Vellimadakunnu": ("M", "ST.JOSEPH'S ENGLISH MEDIUM SCHOOL MARIKUNNU"),
    "St Philomina's A L P @ Vellimadakunnu": ("M", "St. Filomina's A. L. P. S."),
    "A M L P School @ Cheruvatta": ("M", "AMLPS Cheruvatta"),
    "Amrita Vidyalayam @ Vellimadakunnu": ("CBSE", 5),
    "Govt H S @ Nallalam": ("M", "G H S Nallalam"),
    "Govt H S (U P Section) @ Nallalam": ("M", "G H S Nallalam"),
    "Nallalam A U P School @ Areekad": ("M", "Nallalam A. U P S."),
    "Nallalam A L P School @ Areekad": ("M", "Nallalam A. L. P. S. Areekkad"),
    "G L P School @ Pallikandi": ("M", "G. L. P. S. Pallikandi"),
    "Ganapath H S @ East Kallai": ("M", "G. G. H. S.S Kallai"),
    "Ganapath H S S @ East Kallai": ("M", "G. G. H. S.S Kallai"),
    "Ganapath L P School @ East Kallai": ("M", "G. G. L. P. S. East Kallai"),
    "Govt U P School @ Kallai": ("M", "G. U. P. S. Kallai"),
    "Govt U P School @ Panniyankara": ("M", "G. U. P. S. Panniyankara"),
    "Ganapath L P School @ West Kallai": ("M", "Ganapath L. P. S. West Kallai"),
    "Sankaravilasam A L P School @ Kannancherry": ("M", "Sankaravilasam A. L. P. S"),
    "G L P School @ Kappakkal": ("M", "G. L. P. S. Kappakkal"),
    "Govt H S Payyanakkal @ Payyanakkal": ("M", "G. V. H. S. S. Payyanakkal"),
    "Govt V H S S @ Payyanakkal": ("M", "G. V. H. S. S. Payyanakkal"),
    "Govt U P School @ Kundungal": ("M", "G. U. P. S. Kundungal"),
    "A.L.P.School @ Francis Road": ("M", "Francis Road A. L. P. S"),
    "Himayathul Islam HS @ Silk Street": ("M", "Himayathul Islam H. S. S"),
    "St.Joseph's Boys HS @ Convent Road": ("M", "St. Joseph's Boys' H. S. S. Calicut"),
    "St.Joseph's Boys H.S.S @ Convent Road": ("M", "St. Joseph's Boys' H. S. S. Calicut"),
    "St.Joseph's Boys HS (U.P.Section) @ Convent Road": ("M", "St. Joseph's Boys' H. S. S. Calicut"),
    "Govt.U.P.School @ West Vellayil": ("M", "G. U. P. S. Vellayil West"),
    "Govt.Fisheries U.P.School @ Vellayil": ("M", "G. F. U. P. S. Vellayil"),
    "Sree Gujarath Vidyalaya @ Beach Road": ("M", "Sree Gujarathi Vidyalaya H. S. S"),
    "St.Joseph's Anglo Indian Girls H.S. @ Convent Road": ("M", "St. Joseph`s Anglo Indian Girls H. S. S"),
    "M.C.C.L.P.School @ Nadakkav": ("M", "M. C. C. L. P. S"),
    "M.C.C.H.S.S @ Nadakkav": ("M", "M. C. C. H.S.S .Calicut"),
    "Providence Girls L.P.School @ Gandhi Road": ("M", "Providence L. P. S"),
    "Providence Girls H.S.S. @ Gandhi Road": ("M", "Providence Girls H. S. S"),
    "Prividence Girls H.S @ Gandhi Road": ("M", "Providence Girls H. S. S"),
    "G.L.P.School @ Vellayil East": ("M", "G. L. P. S. Vellayil East"),
    "St.Angela's A.U.P.School @ Convent Road": ("M", "St. Angelas A. U. P. S."),
    "St.Antony's A.U.P.School @ Convent Road": ("M", "St.Antonys A. U. P. S."),
    "Govt.Model H.S @ Manachira": ("M", "Govt Model H. S. S. Kozhikode"),
    "Govt.Model H.S.S @ Manachira": ("M", "Govt Model H. S. S. Kozhikode"),
    "CSI E.M.L.P.School @ Manachira": ("M", "C. S. I. E. M. School."),
    "B.E.M.A.L.P.School @ Manachira": ("M", "B. E. M. L. P. School Kozhikode"),
    "B.E.M.Girls High School @ Manachira": ("M", "B. E. M. G. H. S. S. Calicut"),
    "B.E.M.Girls L.P.School @ Manachira": ("M", "B. E. M. Girls L. P. S"),
    "Govt.T.T.I @ Kozhikode": ("M", "GTTI(Men) Kozhikode"),
    "B.E.M.U.P.School @ Puthiyara": ("M", "B. E. M. U. P. S Puthiyara"),
    "Ayyathan Memorial English Medium School @ Chinthavalapp": ("M", "Dr.Ayyathan Gopalan M. E. M. H. S"),
    "G.U.P.School @ Chinthavalapp": ("M", "G. U. P. S. Chindhavalappu"),
    "Umbichi Haji H.S. @ Chaliyam": ("M", "U. H. H. S. S. Chaliyam"),
    "Umbichi Haji H.S.(UP Section) @ Chaliyam": ("M", "U. H. H. S. S. Chaliyam"),
    "P.B.M.English Medium School @ Chaliyam": ("M", "Hajee P. B. M. K. U. P. S. Chaliyam"),
    "Govt.Fisheries L.P.School @ Chaliyam": ("M", "Govt. Fisheries L. P. S. Chaliyam"),
    "M.M.L.P.School @ Chaliyam": ("M", "M. M. L. P. S. Chaliyam"),
    "Calicut Girls H.S.S. @ Kundungal": ("M", "Calicut Girls H.S.S."),
    "Calicut Girls V.H.S.S. @ Kundungal": ("M", "Calicut Girls H.S.S."),
    "Calicut Girls H.S @ Kundungal": ("M", "Calicut Girls H.S.S."),
    "St.Michael's Girls H.S.S. @ West Hill": ("M", "St. Michael's H. S.S Westhill"),
    "St.Michael's Girls H.S. @ West Hill": ("M", "St. Michael's H. S.S Westhill"),
    "St.Michael's Girls E.M.L.P.School @ West Hill": ("M", "St.Michael's EM School Westhill"),
    "Little Daffodils English Medium School @ West Hill": ("CBSE", 42),
    "Govt.Technical H.S. @ West Hill": ("M", "TECHNICAL HS KOZHIKODE"),
    "B.E.M.U.P.School @ Bilathikulam": ("M", "B. E. M. U. P. S Bilathikulam"),
    "Thumbayil A.M.L.P.School @ Kolathara Chungam": ("M", "A. M. L. P. S. Thumbayil"),
    "Atmavidyasangam A.U.P.School @ Kolathara": ("M", "Athmavidya Sangham U. P .S., Cheruvannur"),
    "Kacheriparamba A.M.L.P.School Kannattikulam @ Kannattikulam": ("M", "Kacheripparamba A. M. L. P. S. Kolathara"),
    "T.M.A.L.P.School @ Kolathara": ("M", "T.M.Madrassa A.L.P.S. Kolathara"),
    "C.H.S.S.High School Modern Bazar @ Kolathara": ("M", "Calicut H. S. S. For Handicapped, Kolathara"),
    "Calicut Orphanage H.S @ Kolathara": ("D", 1020),
    "Calicut Orphanage H.S.S @ Kolathara": ("D", 1020),
    "St.Francis English Medium School @ Kundayithode": ("ICSE", "KE111"),
    "G.L.P.School @ Thoppayil": ("M", "G. L. P. S.Thoppayil"),
    "Govt.U.P.School @ West Hill Chungam": ("M", "G. U. P. S. Westhill"),
    "Al Harmain English Medium School @ Puthiyangadi": ("CBSE", 1),
    "Govt.L.P.School @ Puthiyangadi": ("M", "K T Muhammed Smaraka G L P S PUTHIYANGADI"),
    "B.E.M.U.P.School @ Puthiyangadi": ("M", "B. E. M. U. P. S. Puthiyangadi"),
    "M.E.S.Central School @ Pavangad": ("CBSE", 57),
    "Puthur A.U.P.School @ Pavangad": ("M", "A. U. P. S. Puthur"),
    "Venerini English Medium School @ BC Road": ("M", "Venerini E. M. H. S. S."),
    "Govt.L.P.School @ West Nallur": ("M", "G. L. P. S. West Nallur"),
    "Govt.M.L.P.School @ Karuvanthiruthi": ("M", "G. M. L. P. S. Karuvanthuruthi"),
    "B.M.O.U.P.School @ Karuvanthiruthi": ("M", "B. M. O. U. P. S. Karuvanthuruthi"),
    "Crescent Public School @ Chaliyam": ("CBSE", 16),
    "Govt.L.P.School @ Kadalundi": ("M", "G. L. P. S. Kadalundi"),
    "A.L.P.School @ Kadalundi": ("M", "Kadalundi A. L. P. S."),
    "A.M.L.P.School @ Kadalundi": ("M", "Kadalundi A. M. L. P. S."),
    "Govt UPSchool @ Paimbra": ("M", "G H S S Payambra"),
    "ALPSchool @ Palathu": ("M", "A. L. P. S. Palath"),
    "Govt.M.U.P.School @ Puthiyangadi": ("M", "G. M. U. P. S. Puthiyangadi"),
    "Govt.Fisheries H.S @ Puthiyappa": ("M", "G. F. H. S. S. Puthiyappa"),
    "Govt.Fisheries H.S.S @ Puthiyappa": ("M", "G. F. H. S. S. Puthiyappa"),
    "A.M.L.P.School @ Puthiyanirath": ("M", "A. M. L. P. S. Puthiyanirathu"),
    "National A.L.P.School @ Puthiyanirath": ("M", "National A. L. P. S. Elathur"),
    "Sethu Sitharam A.L.P.School @ Chettikulam": ("M", "Sethu Sitharam A. L. P. S."),
    "C.M.C.Girls H.S. @ Elathur": ("M", "C. M. C. Girls. H. S. Elathur"),
    "A.P.A.L.P.School @ Elathur": ("M", "A. P. L. P. S. Elathur"),
    "G.M.L.P.School @ Elathur": ("M", "G. M. L. P. S. Elathur"),
    "C.M.C.Boys H.S @ Elathur": ("M", "C. M. C. Boys. H. S. Elathur"),
    "C.M.C.Boys H.S(U.P.Section) @ Elathur": ("M", "C. M. C. Boys. H. S. Elathur"),
    "Karuna School @ Eranjipalam": ("M", "Karuna Speech and Hearing H.S.S,Eranhipalam"),
    "Govt.H.S @ Karapparamba": ("M", "G. H. S.S Karaparamba"),
    "Govt.H.S(U.P Section) @ Karapparamba": ("M", "G. H. S.S Karaparamba"),
    "Govt.L.P.School @ Karapparamba": ("M", "G. L. P. S. Karaparamba"),
    "Govt.H.S.S. @ Karapparamba": ("M", "G. H. S.S Karaparamba"),
    "A.M.U.P.School @ Karapparamba": ("M", "Atma A. U. P. S. Karaparamba"),
    "ATMA A.U.P.School @ Karapparamba": ("M", "Atma A. U. P. S. Karaparamba"),
    "Kendriya Vidyalaya NO1 @ East Hill": ("CBSE", 40),
    "Govt.H.S. @ East Hill": ("M", "G. H. S. S. Easthill"),
    "Prestige Public School @ Pattelthazham": ("CBSE", 68),
    "K.C.M.A.U.P.School @ Kachilat": ("M", "K. C. M. U. P. S. Kachilatt"),
    "Chinmaya Vidyalaya E.M.H.S. @ Thpndaud": ("M", "Chinmaya E. M. H. S. S."),
    "Govt.Girls H.S.S. @ Parayancheri": ("M", "Govt. Girls H. S. Parayancheri"),
    "Govt.L.P.School @ Parayancheri": ("M", "G. L. P. S. Parayancheri"),
    "Govt.Boys H.S. @ Parayancheri": ("M", "Govt. Boys H. S.S. Parayanchery & G.V.H.S.S Puthiyara"),
    "Govt.H.S.S @ Parayancheri": ("M", "Govt. Boys H. S.S. Parayanchery & G.V.H.S.S Puthiyara"),
    "Govt.Vocational H.S.S. @ Puthiyara": ("M", "Govt. Boys H. S.S. Parayanchery & G.V.H.S.S Puthiyara"),
    "Saraswathi Vidyanikethan E.M.S. @ Pantheerankav": ("M", "Saraswathi Vidya Nikethan English Medium High School, Pantheerankavu"),
    "A.U.P.School @ Pantheerankav": ("M", "A. U. P. S. Pantheerankavu"),
    # only high school in Pantheerankavu in the directories (listed there as Aided)
    "Govt.H.S.(UP Section) @ Pantheerankav": ("M", "Pantheerankave H. S."),
    "Govt.H.S.S @ Pantheerankav": ("M", "Pantheerankave H. S."),
    "Niveditha Vidyapeedam E.M.S. @ Pantheerankav": ("M", "NIVEDITHA VIDYA PEEDAM ENGLISH MEDIUM HIGH SCHOOL"),
    "Hidaya Public School @ Manakkadavu": ("CBSE", 28),
    "Kunnamkulangara A.U.P.School @ Manakkadavu": ("M", "A. M. U. P. S. Kunnamkulangara"),
    "Kunnamkulangara A.L.P.School @ Manakkadavu": ("M", "A. L. P. S. Kunnamkulangara"),
    "Kailmadam A.M.L.P.School @ Pantheerankav": ("M", "A. M. L. P. S. Kailamadam"),
    "A.M.U.P.School @ Puthurmadam": ("M", "A. M. U. P. S. Puthurmadam"),
    "A.M.U.P.School(LP Section) @ Puthurmadam": ("M", "A. M. U. P. S. Puthurmadam"),
    "A.L.P.School @ Perumanna": ("M", "A. L. P. S. Perumanna"),
    "Vidyatmika Public School @ Perumanna": ("CBSE", 98),
    "EMS H.S. @ Perumanna": ("M", "E M S Govt High School,Perumanna"),
    "EMS H.S.S @ Perumanna": ("M", "E M S Govt High School,Perumanna"),
    # same institution logged twice under different place names
    "Brains College @ Kozhikode": ("A", "Brains College @ Calicut"),
    "A.M.L.P.School @ Paramba": ("M", "A. M. L. P. S. Arathilparamba"),
}

AREAS = ["Kozhikode South", "Kozhikode North", "Beypore", "Elathur", "Kunnamangalam"]

# Fallback area for Arshad schools that are not in any directory (private/new/anganwadi)
PLACE_AREA = {}
for area, places in {
    "Kozhikode South": """Meenchanda|Thiruvannur|Kottummal, Thiruvannur|Kannancheri|Kannancherry|Chalappuram|
        Chalappuaram|Thali|Pokkunn|Thalikkulangara|Thalakulangara|Francis Road|Francis Roade|Kaloor Roade|
        Mooriyad|Aazhchavattom|Pattelthazham|Kommeri|Valayanad|Puthiyapalam|Kinassery|Kacherikunn|Parappil|
        Kothipalam|Nainamvalapp|Nadi Nagar|Chakkumkadavu|Kallai|East Kallai|West Kallai|Panniyankara|Kappakkal|
        Payyanakkal|Payyanikal|Pallikandi|Mannari|Vattakkinar|Vattakinnar|Kundungal|Silk Street|Convent Road|
        Beach Road|Thangals Road|Mukhadar|Kuttichira|Manachira|Puthiyara|Chinthavalapp|West Mankav|Kachilat|
        Nellikode|Thpndaud|Parayancheri|BC Road|Calicut|Kozhikode|Cherutti|West Baazar|Kuthukall""",
    "Kozhikode North": """Kottooli|Civil Station|Malaparamba|Vellimadakunnu|Nadakkav|Gandhi Road|Vellayil|
        West Vellayil|Vellayil East|West Hill|West Hill Chungam|Bilathikulam|Thoppayil|Karapparamba|
        Eranjipalam|East Hill|Puthiyangadi""",
    "Beypore": """Mathottam|Arakkinar|Arakinnar|Beypore|Beypore Port|Naduvattom|Naduvattom Beypore|Marad|
        West Beypore|Chaliyam|Kadalundi|Karuvanthiruthi|West Nallur|Nallalam|Nallalam Baazar|Areekad|Kolathara|
        Kolathara Chungam|Kannattikulam|Modern Bazar|Kundayithode""",
    "Elathur": "Elathur|Puthiyappa|Puthiyanirath|Chettikulam|Pavangad|Paimbra|Palathu|Cheruvatta|",
    "Kunnamangalam": """Odumbra|Olavanna|Iringallur|Kambilipparamba|Mathara|Pantheerankav|Manakkadavu|
        Kailamadam|Puthurmadam|Perumanna|Paramba|Poovattuparamb|Pallithazham""",
}.items():
    for p in places.split("|"):
        PLACE_AREA[p.strip()] = area

# Elathur and Kunnamangalam constituencies are much bigger than Arshad's route; only the
# localities he actually works in are counted (the rest is Basheer's rural beat).
ROUTE_KEYWORDS = {
    "Elathur": ["elathur", "puthiyappa", "puthiyanirath", "eranhi", "puthiyangadi", "puthur", "sethu sitharam",
                "palath", "payambra", "cheruvatta", "mokavoor"],
    "Kunnamangalam": ["pantheeran", "olavanna", "perumanna", "puthurmadam", "odumbra", "iringallur", "kailamadam",
                      "poovattuparamb", "kunnamkulangara", "palazhi", "kodal", "moorkkanad", "thumbayil",
                      "vellayicode", "koodathumpara", "arathilparamba", "kambliparamba", "paingottupuram",
                      "calicut islamic residential", "payyadimeethal"],
}

# CBSE schools (s.no) inside Arshad's areas -> area (checked by address / PIN)
CBSE_AREA = {1: "Kozhikode North", 3: "Beypore", 5: "Kozhikode North", 9: "Kunnamangalam",
             12: "Kozhikode North", 13: "Elathur", 16: "Beypore", 21: "Kozhikode South", 28: "Kunnamangalam",
             37: "Kozhikode North", 40: "Kozhikode North", 41: "Kozhikode South", 42: "Kozhikode North",
             47: "Kozhikode North", 57: "Elathur", 62: "Beypore", 66: "Kozhikode North", 68: "Kozhikode South",
             76: "Kunnamangalam", 78: "Kozhikode North", 84: "Kozhikode South", 86: "Kozhikode South",
             91: "Kunnamangalam", 92: "Kunnamangalam", 95: "Kozhikode North", 98: "Kunnamangalam"}
ICSE_AREA = {"KE159": "Kozhikode South", "KE111": "Beypore", "KE089": "Kozhikode North"}

# Deepika schools that are not in the master list but sit in Arshad's areas
DEEPIKA_EXTRA_AREA = {325: "Beypore", 1020: "Beypore", 1126: "Kozhikode South"}

# Free-pass feedback rows that belong to Arshad's areas: person phone -> matched school key
# ("A:<arshad key>" for a school Arshad visited, "M:<master name>" otherwise)
FEEDBACK_MATCH = {
    "9846438183": "A:A.M.L.P.School @ Paramba",
    "9072512346": "A:Nallalam A U P School @ Areekad",
    "8848939060": "A:Govt H S @ Kinassery",
    "7293786313": "A:Markaz E M School @ Pokkunn",
    "9446164049": "M:J. D. T. Islam .A.L. P. S. Merikkunnu",
}
